config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  resources :task_lists do
  	resources :task_items do
  		member do
  			patch :complete
  		end
  	end
  end

  root "home#landing"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task_item.rb
# == Schema Information
#
# Table name: task_items
#
#  id           :bigint(8)        not null, primary key
#  content      :string
#  task_list_id :bigint(8)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  completed_at :datetime
#

class TaskItem < ApplicationRecord
  belongs_to :task_list
  belongs_to :user

  def completed?
  	!completed_at.blank?
  end
end

app/models/task_list.rb
# == Schema Information
#
# Table name: task_lists
#
#  id          :bigint(8)        not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class TaskList < ApplicationRecord
	has_many :task_items
	belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :task_lists
  has_many :task_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :check_user

  def landing
  end

  private

  def check_user
  	if user_signed_in?
  		redirect_to task_lists_path
  	else
  		root_path
  	end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	protected

	def after_sign_up_path_for(resource)
	  task_lists_path
	end

	def after_sign_in_path_for(resource)
	  task_lists_path
	end
end

app/controllers/task_items_controller.rb
class TaskItemsController < ApplicationController
	before_action :set_task_list
	before_action :set_task_item, except: [:create]

	def create
		@task_item = @task_list.task_items.create(task_item_params)
		redirect_to @task_list
	end

	def destroy
		if @task_item.destroy
			flash[:success] = "Task List item was deleted."
		else
			flash[:error] = "Task List item could not be deleted."
		end
		redirect_to @task_list
	end

	def complete
		@task_item.update_attribute(:completed_at, Time.now)
		redirect_to @task_list, notice: "Task item completed"
	end

	private

	def set_task_list
		#@task_list = TaskList.find(params[:task_list_id])
		@task_list = current_user.task_lists.find(params[:task_list_id])
	end

	def set_task_item
		#@task_item = @task_list.task_items.find(params[:id])
		@task_item = current_user.task_list.task_items.find(params[:id])
	end

	def task_item_params
		params[:task_item].permit(:content)
	end

end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController

  before_action :authenticate_user!, except: [:landing]
  before_action :set_task_list, only: [:show, :edit, :update, :destroy]

  def index
    #@task_lists = TaskList.all
    @task_lists = current_user.task_lists
  end

  def show
  end

  def new
    #@task_list = TaskList.new
    @task_list = current_user.task_lists.build
  end

  def edit
  end

  def create
    #@task_list = TaskList.new(task_list_params)
    @task_list = current_user.task_lists.build(task_list_params)

    respond_to do |format|
      if @task_list.save
        format.html { redirect_to @task_list, notice: 'Task list was successfully created.' }
        format.json { render :show, status: :created, location: @task_list }
      else
        format.html { render :new }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        format.html { redirect_to @task_list, notice: 'Task list was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_list }
      else
        format.html { render :edit }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Task list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    def task_list_params
      params.require(:task_list).permit(:title, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/task_items_helper.rb
module TaskItemsHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/views/home/landing.html.erb
<% provide(:page_title, "Home") %>

<div class="container">
	<div class="row my-5">
		<div class="col-sm-6 offset-md-3">
			<div class="text-center">
				<h1 class="title">Welcome to TasksApp</h1>
				<p class="lead mb-5">An app that will make your life easier!</p>	
				<hr>
				<%= link_to "Log In", user_session_path, class: 'nav-link links' %> |
				<%= link_to "Sign Up", new_user_registration_path, class: 'nav-link links' %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | TasksApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">    
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container mt-3">
      <% if flash.any? %>
        <% flash.keys.each do |key| %>
          <div class="alert alert-<%= key.to_s %> mb-0" role="alert" style="color: #000;background-color: rgb(204, 229, 255)">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span> 
            </button>
            <%= flash[key] %>
          </div>
        <% end %>
      <% end %>
    </div>
    
    <div class="<%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to task_lists_path do %>
    <span class="navbar-brand">
      <span class="heavy">Tasks</span>App
    </span>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item name">
          <%= link_to current_user.email, nil, class: "nav-link #{yield(:tasks_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Tasks", task_lists_path, class: "nav-link #{yield(:tasks_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Task List", new_task_list_path, class: "nav-link #{yield(:new_tasks_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log In", user_session_path, class: "nav-link #{yield(:login_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link #{yield(:signup_active)}" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/task_items/_form.html.erb
<%= form_for([@task_list, @task_list.task_items.build]) do |f| %>
	<div class="row">
		<div class="col-sm-8">
			<%= f.text_field :content, placeholder: "New Task", class: 'form-control' %>
		</div>
		<div class="col-sm-4">
			<%= f.submit "Add Task", class: 'btn btn-outline-primary btn-md font-weight-bold' %>
		</div>
	</div>
<% end %>

app/views/task_items/_task_item.html.erb
<div class="row clearfix">
	<% if task_item.completed? %>
		<div class="complete">
			<%= link_to complete_task_list_task_item_path(@task_list, task_item.id), method: :patch do %>
				<i style="opacity: 0.4;" class="fas fa-check"></i>
			<% end %>
		</div>
		<div class="task_item">
			<p style="opacity: 0.4;"><s><%= task_item.content %></s></p>
		</div>
		<div class="trash">
			<%= link_to task_list_task_item_path(@task_list, task_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fas fa-trash-alt"></i>
			<% end %>
		</div>
	<% else %>
		<div class="complete">
			<%= link_to complete_task_list_task_item_path(@task_list, task_item.id), method: :patch do %>
				<i class="fas fa-check"></i>
			<% end %>
		</div>
		<div class="task_item">
			<p><%= task_item.content %></p>
		</div>
		<div class="trash">
			<%= link_to task_list_task_item_path(@task_list, task_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fas fa-trash-alt"></i>
			<% end %>
		</div>
	<% end %>
</div>

app/views/task_lists/_form.html.erb
<%= form_with(model: task_list, local: true) do |form| %>
  <% if task_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
      <% task_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-3 text-left">
    <%= form.label "Title:", class: 'font-weight-bold' %><br>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field my-3 text-left">
    <%= form.label "Description:", class: 'font-weight-bold' %><br>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="text-right">
    <%= link_to 'Back', task_lists_path, class: 'btn btn-outline-danger btn-md font-weight-bold' %>
    <%= form.submit "Task", class: 'btn btn-outline-primary btn-md font-weight-bold' %>
  </div>
<% end %>

app/views/task_lists/edit.html.erb
<% provide(:page_title, "Edit " + @task_list.title) %>
<% provide(:tasks_active, 'active') %>

<div class="container">
	<div class="row my-5">
		<div class="col-sm-6 offset-sm-3">
			<h1 class="title text-center">Edit <%= @task_list.title.capitalize %></h1>
			<div class="forms">
				<%= render 'form', task_list: @task_list %>
			</div>
		</div>
	</div>
</div>

app/views/task_lists/index.html.erb
<% provide(:page_title, "My Tasks") %>
<% provide(:tasks_active, 'active') %>

<div class="container">
	<div class="row my-5">
		<div class="col-sm-6 offset-sm-3 show-view">
			<% @task_lists.each do |task_list| %>
			<div class="index_row clearfix text-center">
			  <h2 class="todo_list_title font-weight-bold"><%= link_to task_list.title, task_list %></h2>
			  <hr class="mx-5">
			  <p class="todo_list_sub_title"><%= task_list.description %></p>
			</div>
			<br>
			<% end %>
		</div>
	</div>
</div>

app/views/task_lists/new.html.erb
<% provide(:page_title, "New Task List") %>
<% provide(:new_tasks_active, 'active') %>

<div class="container">
	<div class="row my-5">
		<div class="col-sm-6 offset-sm-3">
			<div class="forms">
				<h1 class="title">New Task List</h1>
				<%= render 'form', task_list: @task_list %>
			</div>
		</div>
	</div>
</div>

app/views/task_lists/show.html.erb
<% provide(:page_title, @task_list.title.capitalize) %>
<% provide(:tasks_active, 'active') %>

<div class="container">
	<div class="row my-5">
		<div class="col-sm-6 offset-sm-3 show-view">
			<h1 class="title"><%= @task_list.title %></h1>
			<p class="lead"><%= @task_list.description %></p>
			<!--<%#= render @task_list.task_items %>
			<%#= render "task_items/form" %>-->
			<div class="links">
				<%= link_to 'Edit', edit_task_list_path(@task_list) %> |
				<%= link_to 'Delete', task_list_path(@task_list), method: :delete, data: { confirm: "Are you sure?" }
			 %>
			</div>
		</div>
	</div>
</div>